#!/bin/bash

cliversion='1.3.0'
installerversion='1.0'
newversion=$(curl -s https://raw.githubusercontent.com/jonjohnston/okta-awscli/okta-vault-cli/version)
newinstaller=$(curl -s https://raw.githubusercontent.com/jonjohnston/okta-awscli/okta-vault-cli/installerversion)
if [ "$newversion" != "$cliversion" ]; then
        echo "New version available. Please re-run okta-cred-installer.sh"
fi
if [ "$newinstaller" != "$installerversion" ]; then
	echo "New installer available. Please download: "
fi
#cp ~/.okta-vault-aws ~/.okta-aws
#Kill metadata blocker
export AWS_METADATA_URL="http://localhost/not/existent/url"

oktap=""

while getopts a: option
do
	case "${option}"
	in
		a) oktap=${OPTARG};;
	esac
done

if [ -z "$oktap" ]; then
	echo "Please run with -a parameter specifying account"
	exit 1
fi

okta-awscli --okta-profile $oktap --force
