#!/bin/bash

#Kill metadata blocker
export AWS_METADATA_URL="http://localhost/not/existent/url"

oktap=""

while getopts a: option
do
	case "${option}"
	in
		a) oktap=${OPTARG};;
	esac
done

if [ -z "$oktap" ]; then
	echo "Please run with -a parameter specifying account"
	exit 1
fi

okta-awscli --okta-profile $oktap --force
